### ISSUE TITLE
添加 .gitignore 文件

### ISSUE THREAD

**Issue by happypeter** [shindouhiro/Modern#2]
https://github.com/shindouhiro/Modern/compare/2dfd3d3948...c32e64fd79#diff-b2e6d714552f69b15f28d4faff32e749R2

中把 node_modules 中的文件都添加到版本控制中了，这个是不好的。可以这样

```
mv  node_modules  ..
git add -A
git commit -m"rm node_modules"
mv ../node_modules .
```

然后创建 .gitignore 文件，里面填写

```
node_modules
```

这样，以后进行版本控制的时候，这些 node_modules 内容就不会被添加到新版本中了。

参考：https://github.com/happypeter/qd/blob/master/.gitignore

**Comment by happypeter** [comment]
另外，如果想补一下 git 的基础，欢迎收看：http://www.imooc.com/view/390

**Comment by shindouhiro** [comment]
OK

**Comment by happypeter** [comment]
well done!
